GECI distance
IslasGECI/geci_distance pull request #2
Opened 2020-06-19 16:14 UTC by nepito

- [ ] Guía de estilo

2020-06-19 17:16 UTC, nepito reviewed
@islasfernando no puedo solicitarte cambios

2020-06-19 17:16 UTC, nepito commented on Dockerfile
> +    lmfit \
Por favor ponlo en orden alfabético

2020-06-19 17:16 UTC, nepito commented on geci_distance/geci_distance.py
> +    def normalize_pdf(self, pdf):
¿Por qué normalizas una _pdf_ no siempre está normilizada? ¿por qué el índice cero te da el valor máximo?

2020-06-19 17:16 UTC, nepito commented on geci_distance/geci_distance.py
> +    return (1 - np.exp(-(x/sigma)**(-beta)))
¡¡¡Loco!!! El mutante 4 cambia `(x/sigma)` por `(x*sigma)` y no marca error la prueba, eso está muy loco

2020-06-19 17:16 UTC, nepito commented on test/test_geci_distance.py
> +        self.assertEqual(output, 0.6321205588285577)
el tío Bob recomienda usar `assertAlmostEqual` cuando evaluas reales:
```suggestion
        self.assertAlmostEqual(output, 0.18126924)
```

2020-06-19 17:16 UTC, nepito commented on test/test_geci_distance.py
> +        self.Beta: int = 0
Cambiando a:
```suggestion
        self.Beta: int = 1
```
y el `self.assertAlmostEqual(output, 0.18126924)` ya cazas dos mutantes más

2020-06-19 17:16 UTC, nepito commented on Makefile
> +mutation:
Alguna vez hizo una encuesta Evaristo y ganó `make mutants` tal vez lo podrías cambiar para irlo probando
```suggestion
mutants:
```

2020-06-19 17:16 UTC, nepito commented on Makefile
> +.PHONY: clean install mutation tests
```suggestion
.PHONY: clean install mutants tests
```

2020-06-19 17:16 UTC, nepito commented on geci_distance/geci_distance.py
> +        return self.norm_hist, self.bins_mid_points
Pareciera que no es necesario regresarlas, ya que las guardan en las propiedades del objeto `self.norm_hist` y  `self.bins_mid_points`. Es decir ¿qué pasa si borras esta línea?
```suggestion
```

2020-06-22 18:27 UTC, devarops requested changes
Por favor agrega verificación automática del formato mediante Black

2020-06-22 18:27 UTC, evaristor commented on .github/workflows/actions.yml
> +      run: docker run islasgeci/geci_distance make
```suggestion
      run: docker run islasgeci/geci_distance make
    - name: Verifica el formato
      run: docker run islasgeci/dummy_transformations make format
```

2020-06-22 18:27 UTC, evaristor commented on Makefile
> +
```suggestion

format:
	black --check geci_distance
	black --check tests

```

2020-06-22 18:27 UTC, evaristor commented on Dockerfile
> +    mutmut \
```suggestion
    black \
    mutmut \
```

2020-06-22 19:17 UTC, devarops requested changes
Por favor renombra el directorio `test/` por `tests/`

2020-06-22 20:37 UTC, islasfernando commented on geci_distance/geci_distance.py
> +    def normalize_pdf(self, pdf):
creo que el nombre puede ser el error, en realidad NO es una PDF estrictamente hablando. Puede quedar mejor `normalize_histogram`. El indice 0 es el valor máximo de acuerdo a la suposición de que la probabilidad de detección cerca de la línea es 100%.

2020-06-23 16:26 UTC, evaristor commented
¿Sabes que significa esto. @islasfernando?

![image](https://user-images.githubusercontent.com/3461018/85428911-c2d5b880-b532-11ea-9d1b-bb4c936669d2.png)

2020-06-23 16:36 UTC, islasfernando commented
> ¿Sabes que significa esto. @islasfernando?
> 
> ![image](https://user-images.githubusercontent.com/3461018/85428911-c2d5b880-b532-11ea-9d1b-bb4c936669d2.png)

No sé, porque salen?

2020-06-23 16:38 UTC, evaristor commented
> No sé, porque salen?

Le pase un par de _linters_ (flake8 y pylint), pero no estoy seguro sobre como interpretar los resultados

2020-06-23 16:38 UTC, nepito commented
> ¿Sabes que significa esto. @islasfernando?
> 
> ![image](https://user-images.githubusercontent.com/3461018/85428911-c2d5b880-b532-11ea-9d1b-bb4c936669d2.png)

Nooooooo ¿te dice que andas de fantoche cargando cosas que no ocupas?

2020-06-23 17:00 UTC, evaristor commented
> Nooooooo ¿te dice que andas de fantoche cargando cosas que no ocupas?

@islasfernando: ¿No usas `pandas` en `geci_distance.py`?

2020-06-23 17:04 UTC, islasfernando commented
> > Nooooooo ¿te dice que andas de fantoche cargando cosas que no ocupas?
> 
> @islasfernando: ¿No usas `pandas` en `geci_distance.py`?

No, ya chequé

2020-06-23 18:42 UTC, evaristor commented
> > ¿No usas `pandas` en `geci_distance.py`?
> 
> No, ya chequé

Entonces tal vez sí sean de utilidad los _linters_?

2020-06-23 19:21 UTC, devarops requested changes
Excelente trabajo @islasfernando .

Aquí te dejo mi revisión

2020-06-23 19:21 UTC, evaristor commented on geci_distance/geci_distance.py
> +import pandas as pd
```suggestion
```

2020-06-23 19:21 UTC, evaristor commented on geci_distance/geci_distance.py
> +import pandas as pd
¿Podemos quitar esta línea?

2020-06-23 19:21 UTC, evaristor commented on geci_distance/geci_distance.py
> +    def initialize_hazard_model(self):
Parece que aquí no usas `self` ¿Sería mejor como función en lugar de método?

2020-06-23 19:21 UTC, evaristor commented on geci_distance/geci_distance.py
> +    def calculate_mid_points(self, bins):
Parece que aquí no usas `self` ¿Sería mejor como función en lugar de método?

2020-06-23 19:21 UTC, evaristor commented on geci_distance/geci_distance.py
> +    def normalize_histogram(self, pdf):
Parece que aquí no usas `self` ¿Sería mejor como función en lugar de método?

2020-06-23 19:21 UTC, evaristor commented on geci_distance/geci_distance.py
> +            return self.sigma, self.beta
¿Qué pasa si no entra al `if`? ¿Qué regresa en ese caso? ¿Es correcto que regrese `self.sigma` y `self.beta` en lugar de `self`?

2020-06-23 19:21 UTC, evaristor commented on geci_distance/geci_distance.py
> +        area, error = integrate.quad(hazard_model, 0, self.width, args=(self.sigma, self.beta))
```suggestion
        area, _ = integrate.quad(hazard_model, 0, self.width, args=(self.sigma, self.beta))
```
Parece que no usas la variable `error`

2020-06-23 19:21 UTC, evaristor commented on geci_distance/geci_distance.py
> +        self.n_obs = n_obs
```suggestion
        self.area = None
        self.beta = None
        self.bins_mid_points = None
        self.detection_probability = None
        self.distances = distances
        self.length = None
        self.n_bins = n_bins
        self.n_obs = n_obs
        self.n_total = None
        self.norm_hist = None
        self.sigma = None
        self.width = None
```

Podríamos definir todos los atributos en el `__init__`?

2020-06-23 19:30 UTC, evaristor commented
@islasfernando: Me llamó la atención que usemos `unittest` en lugar de `pytest`. Entiendo que `pytest` es mejor y más fácil, no? ¿Tú que opinas?

2020-07-21 19:40 UTC, islasfernando commented on geci_distance/geci_distance.py
> +            return self.sigma, self.beta
La idea es ir agregando más modelos, y le doy la posibilidad al usuario de que guarde sigma y beta, aunque no sé si es la mejor forma de hacerlo..

2020-07-21 19:44 UTC, evaristor commented on geci_distance/geci_distance.py
> +            return self.sigma, self.beta
@islasfernando 
OK. Ya entiendo. Entonces debemos regresar una excepción si el modelo seleccionado no está implementado. Buscaré como regresar excepciones en Python

2020-07-21 19:47 UTC, evaristor commented on geci_distance/geci_distance.py
> +            return self.sigma, self.beta
¿Algo así, @islasfernando ?:
```suggestion
            return self.sigma, self.beta
        else:
            raise NameError('InvalidModel')
```

2020-07-21 19:53 UTC, evaristor commented on geci_distance/geci_distance.py
> +            return self.sigma, self.beta
@islasfernando : Otra opción sería quitar el `if` y nombrar esta función `def fit_detection_function_hazard(self)` y cuando en el futuro implementemos el segundo modelo (distinto a `hazard`) entonces agregamos `def fit_detection_function(self, model)` con el `if `. Para no adelantarnos al futuro.

2020-07-21 20:00 UTC, islasfernando commented on geci_distance/geci_distance.py
> +            return self.sigma, self.beta
Va, lo voy a quitar entonces. Gracias @evaristor

2020-07-24 00:14 UTC, nepito commented
Listo @islasfernando por favor apruébala, pues yo no lo puedo hacer, pues yo soy el creador del _pull request_. Me avisas y yo hago _merge_.

2020-07-27 15:25 UTC, islasfernando approved these changes

2020-07-27 15:26 UTC, merged